spring:
  application:
    name: teste-grupo-primo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080

resilience4j:
  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
        cancelRunningFuture: true
    instances:
      activity:
        baseConfig: default

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true

logging:
  file:
    name: ${java.io.tmpdir}/logs/${spring.application.name}.log
  level:
    root: debug